ALTER TABLE vocabulary ADD COLUMN IF NOT EXISTS emoji VARCHAR(10) NOT NULL DEFAULT '';
ALTER TABLE vocabulary ADD COLUMN IF NOT EXISTS example_sentence VARCHAR(500) NOT NULL DEFAULT '';
ALTER TABLE vocabulary ADD COLUMN IF NOT EXISTS example_sentence_vi VARCHAR(500) NOT NULL DEFAULT '';
